name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17
          cache: "maven"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: Login to GitHub Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: mvn -B clean package --file pom.xml
      - name: Build and push CI image
        uses: docker/build-push-action@v5.1.0
        with:
          push: true
          context: .
          tags: ghcr.io/${{ github.repository }}/scality-keycloak:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          github-token: ${{ secrets.GITHUB_TOKEN }}

        #
        # Build SBOM
        #
      - name: Install syft
        run: |
          SYFT_VERSION="1.19.0"
          SYFT_INSTALLER="syft_${SYFT_VERSION}_linux_amd64.deb"
          SYFT_CHECKSUM="f3667d6abfa97a1e5614882f81e0a0b090f0047e0df7025b568fa87b6d95ac58"
          wget https://github.com/anchore/syft/releases/download/v${SYFT_VERSION}/${SYFT_INSTALLER}
          ACTUAL_CHECKSUM=$(sha256sum ${SYFT_INSTALLER} | cut -d ' ' -f1)
          if [ "$ACTUAL_CHECKSUM" != "$SYFT_CHECKSUM" ]; then
            echo "ERROR: Checksum verification failed for ${SYFT_INSTALLER}"
            echo "Expected: ${SYFT_CHECKSUM}"
            echo "Got:      ${ACTUAL_CHECKSUM}"
            exit 1
          fi
          sudo dpkg -i ${SYFT_INSTALLER}

      - name: "build Software Bill of materials (SBOM)"
        run: |
          set -xv
          syft scan dir:./ --source-name=keycloak-extensions --source-version ${{ github.ref_name }} --output cyclonedx-json=scality-keycloak-extensions.tgz.sbom.spdx.json

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target_commitish: ${{ github.sha }}
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          generate_release_notes: true
          files: |
            scality-keycloak-extensions.tgz.sbom.spdx.json
            target/*.jar
